spring:
  datasource:
    url: jdbc:h2:mem:seesaw;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop  # 테스트마다 스키마를 생성/삭제하여 격리성 확보
    properties:
      hibernate:
        highlight_sql: true     # 콘솔 색상 하이라이트(지원 콘솔에서만 표시)
#        use_sql_comments: true  # SQL 주석 출력
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never  # 필요 시 'embedded' 또는 'always'로 변경 (schema.sql/data.sql 사용 시)

logging:
  level:
    root: info
    org.springframework.orm.jpa: debug
    # SQL 문 출력
    org.hibernate.sql: debug
    # 파라미터 바인딩 값 출력(Hibernate 6)
    org.hibernate.orm.jdbc.bind: trace
    # 결과 추출 로깅(선택)
    org.hibernate.orm.jdbc.extract: trace
    # Hibernate 5 호환 로깅(선택적으로 사용)
    org.hibernate.type.descriptor.sql: trace

kr:
  me:
    seesaw:
      filepath: YOUR_PATH
